"""
Intelligence Service — Neo4j graph access.

Executes Cypher generated by the LLM against Neo4j.
Read-only — never runs CREATE/DELETE/SET.
"""
import json
from typing import List, Dict, Any

from neo4j import GraphDatabase

from intelligence_service.core.config import SETTINGS
from intelligence_service.core.logger import logger

_driver = None


def _get_driver():
    global _driver
    if _driver is None:
        _driver = GraphDatabase.driver(
            SETTINGS.NEO4J_URI,
            auth=(SETTINGS.NEO4J_USER, SETTINGS.NEO4J_PASSWORD),
        )
    return _driver


def execute_readonly_cypher(cypher: str, params: Dict[str, Any] = None) -> List[Dict[str, Any]]:
    """Execute a read-only Cypher query and return records as dicts.

    Safety: rejects mutations.
    """
    cypher = cypher.replace("\\n", " ").replace("\\t", " ")
    stripped = cypher.strip().upper()
    for forbidden in ("CREATE ", "DELETE ", "DETACH ", "SET ", "REMOVE ", "MERGE ", "DROP "):
        if forbidden in stripped:
            raise ValueError(f"Forbidden Cypher keyword detected: {forbidden.strip()}")

    driver = _get_driver()
    with driver.session(database=SETTINGS.NEO4J_DATABASE) as session:
        result = session.run(cypher, params or {})
        records = []
        for record in result:
            row = {}
            for key in record.keys():
                val = record[key]
                if hasattr(val, "items"):
                    row[key] = dict(val)
                elif hasattr(val, "isoformat"):
                    row[key] = val.isoformat()
                else:
                    row[key] = val
            records.append(row)
        return records


def get_graph_schema_description() -> str:
    """Return a compact description of the Neo4j graph schema for the LLM."""
    return """
Neo4j Graph Schema (ZeroQue Governance Topology):

Node labels and key properties:
  :Tenant      {tenant_id, name, domain, status}
  :Site        {site_id, name, site_type, currency, timezone, geo, status}
  :Store       {store_id, name, store_type, geo, status}
  :OrgUnit     {org_unit_id, name, code, level, status}
  :User        {user_id, email, display_name, status}
  :Role        {role_id, code, name, status}
  :Permission  {code}
  :Product     {product_id, display_name, sku, item_code, restricted, status}
  :Category    {category_id, name, code, status}
  :Vendor      {vendor_id, name, contact_email, status}
  :CostCentre  {cost_centre_id, name, code, status}
  :ApprovedRange {approved_range_id, name, is_universal, status}
  :Policy      {policy_id, code, name, policy_type, status}

Relationships:
  (:Tenant)-[:HAS_SITE]->(:Site)
  (:Site)-[:HAS_STORE]->(:Store)
  (:Store)-[:STOCKS]->(:Product)
  (:Tenant)-[:HAS_ORG_UNIT]->(:OrgUnit)
  (:OrgUnit)-[:CHILD_OF]->(:OrgUnit)
  (:Tenant)-[:HAS_USER]->(:User)
  (:User)-[:BELONGS_TO]->(:OrgUnit)
  (:User)-[:HAS_ROLE]->(:Role)
  (:Role)-[:GRANTS]->(:Permission)
  (:User)-[:WORKS_AT]->(:Store)
  (:User)-[:ASSIGNED_TO_CC]->(:CostCentre)
  (:User)-[:MANAGES]->(:CostCentre)
  (:Tenant)-[:HAS_APPROVED_RANGE]->(:ApprovedRange)
  (:OrgUnit)-[:GOVERNED_BY]->(:ApprovedRange)
  (:ApprovedRange)-[:INCLUDES]->(:Product)
  (:Product)-[:IN_CATEGORY]->(:Category)
  (:Vendor)-[:SUPPLIES]->(:Product)
  (:Tenant)-[:HAS_PRODUCT]->(:Product)
  (:Tenant)-[:HAS_VENDOR]->(:Vendor)
  (:Tenant)-[:HAS_CATEGORY]->(:Category)
  (:Tenant)-[:HAS_COST_CENTRE]->(:CostCentre)
  (:Policy)-[:ASSIGNED_TO]->(:Tenant | :OrgUnit | :Role)

Note: Only products in approved ranges exist in the graph.
All status fields: 'active' or 'deleted'. Query active entities with {status: 'active'}.
"""
