"""init_core_schema

Revision ID: a74ea1c0df1e
Revises: 
Create Date: 2025-12-08 17:59:50.990890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a74ea1c0df1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS plan_prices')
    op.drop_column('approval_requests', 'approved_amount_minor')
    op.drop_column('approval_requests', 'amount_modification_history')
    op.alter_column('approver_limits', 'daily_limit_minor',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('approver_limits', 'daily_spent_minor',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('approver_limits', 'monthly_limit_minor',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('approver_limits', 'monthly_spent_minor',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('approver_limits', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.drop_index(op.f('ix_approver_limit_tenant'), table_name='approver_limits')
    op.drop_index(op.f('ix_approver_limit_user_cc'), table_name='approver_limits')
    op.create_index('ix_approver_limit_unique', 'approver_limits', ['tenant_id', 'user_id', 'cost_centre_id'], unique=True)
    op.drop_column('approver_limits', 'last_reset_daily')
    op.drop_column('approver_limits', 'last_reset_monthly')
    op.alter_column('cost_centres', 'budget_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('cost_centres', 'spent_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('features', 'usage_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'count'::character varying"))
    op.alter_column('features', 'reset_period',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.drop_column('features', 'unit')
    op.drop_column('features', 'category')
    op.alter_column('instant_budget_requests', 'approved_amount_minor',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('instant_budget_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_instant_budget_requests_created_at'), table_name='instant_budget_requests')
    op.drop_index(op.f('ix_instant_budget_status_expires'), table_name='instant_budget_requests')
    op.alter_column('products', 'tax_rate',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_constraint(op.f('sites_tenant_id_fkey'), 'sites', type_='foreignkey')
    op.drop_column('sites', 'tenant_id')
    op.create_index('ix_subscription_usage_composite', 'subscription_usage', ['tenant_id', 'feature_code', 'period_start'], unique=False)
    op.add_column('tenant_subscriptions', sa.Column('previous_sub_id', sa.Integer(), nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('billing_cycle', sa.String(length=50), nullable=False))
    op.add_column('tenant_subscriptions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tenant_subscriptions', sa.Column('is_trial', sa.Boolean(), nullable=False))
    op.alter_column('tenant_subscriptions', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tenant_subscriptions', 'current_period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tenant_subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_tenant_subscriptions_status'), table_name='tenant_subscriptions')
    op.create_foreign_key(None, 'tenant_subscriptions', 'tenant_subscriptions', ['previous_sub_id'], ['id'])
    op.drop_column('tenant_subscriptions', 'trial_end')
    op.drop_column('tenant_subscriptions', 'status')
    op.add_column('tenants', sa.Column('tenant_name', sa.String(length=200), nullable=False))
    op.add_column('tenants', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('tenants', sa.Column('billing_cycle', sa.String(length=20), nullable=False))
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('tenants_name_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_index(op.f('ix_tenants_tenant_name'), 'tenants', ['tenant_name'], unique=True)
    op.drop_column('tenants', 'tenant_metadata')
    op.drop_column('tenants', 'name')
    op.add_column('user_cost_centres', sa.Column('recurring_budget_minor', sa.BigInteger(), nullable=True))
    op.add_column('user_cost_centres', sa.Column('recurring_period', sa.String(length=20), nullable=True))
    op.add_column('user_cost_centres', sa.Column('last_reset_date', sa.Date(), nullable=True))
    op.add_column('user_cost_centres', sa.Column('next_reset_date', sa.Date(), nullable=True))
    op.add_column('user_roles', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'user_roles', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_logout_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_index(op.f('ix_users_email_lower'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'api_key_expires_at')
    op.drop_column('users', 'api_key_created_at')
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'api_key')
    op.drop_index(op.f('ix_vendors_user_id'), table_name='vendors')
    op.drop_constraint(op.f('vendors_user_id_fkey'), 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vendors_user_id_fkey'), 'vendors', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.create_index(op.f('ix_vendors_user_id'), 'vendors', ['user_id'], unique=False)
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('account_locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('api_key_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('api_key_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email_lower'), 'users', [sa.literal_column('lower(email::text)')], unique=False)
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.drop_column('users', 'last_logout_at')
    op.drop_column('users', 'refresh_token_expires_at')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_tenant_id'), table_name='user_roles')
    op.drop_column('user_roles', 'tenant_id')
    op.drop_column('user_cost_centres', 'next_reset_date')
    op.drop_column('user_cost_centres', 'last_reset_date')
    op.drop_column('user_cost_centres', 'recurring_period')
    op.drop_column('user_cost_centres', 'recurring_budget_minor')
    op.add_column('tenants', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('tenant_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_tenant_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_name_key'), 'tenants', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'billing_cycle')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'registration_number')
    op.drop_column('tenants', 'tenant_name')
    op.add_column('tenant_subscriptions', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tenant_subscriptions', sa.Column('trial_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenant_subscriptions', type_='foreignkey')
    op.create_index(op.f('ix_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False)
    op.alter_column('tenant_subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tenant_subscriptions', 'current_period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tenant_subscriptions', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('tenant_subscriptions', 'is_trial')
    op.drop_column('tenant_subscriptions', 'is_active')
    op.drop_column('tenant_subscriptions', 'billing_cycle')
    op.drop_column('tenant_subscriptions', 'previous_sub_id')
    op.drop_index('ix_subscription_usage_composite', table_name='subscription_usage')
    op.add_column('sites', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sites_tenant_id_fkey'), 'sites', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_products_vendor_id'), table_name='products')
    op.alter_column('products', 'tax_rate',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_instant_budget_status_expires'), 'instant_budget_requests', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_instant_budget_requests_created_at'), 'instant_budget_requests', ['created_at'], unique=False)
    op.alter_column('instant_budget_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('instant_budget_requests', 'approved_amount_minor',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('features', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('features', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('features', 'reset_period',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.alter_column('features', 'usage_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'count'::character varying"))
    op.alter_column('cost_centres', 'spent_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cost_centres', 'budget_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('approver_limits', sa.Column('last_reset_monthly', sa.DATE(), server_default=sa.text("date_trunc('month'::text, (CURRENT_DATE)::timestamp with time zone)"), autoincrement=False, nullable=True))
    op.add_column('approver_limits', sa.Column('last_reset_daily', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
    op.drop_index('ix_approver_limit_unique', table_name='approver_limits')
    op.create_index(op.f('ix_approver_limit_user_cc'), 'approver_limits', ['user_id', 'cost_centre_id'], unique=False)
    op.create_index(op.f('ix_approver_limit_tenant'), 'approver_limits', ['tenant_id'], unique=False)
    op.alter_column('approver_limits', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('approver_limits', 'monthly_spent_minor',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('approver_limits', 'monthly_limit_minor',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('approver_limits', 'daily_spent_minor',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('approver_limits', 'daily_limit_minor',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('approval_requests', sa.Column('amount_modification_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('approval_requests', sa.Column('approved_amount_minor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('plan_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'GBP'::character varying"), autoincrement=False, nullable=False),
    sa.Column('price_monthly_minor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quarterly_discount_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('5.0'), autoincrement=False, nullable=False),
    sa.Column('yearly_discount_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('10.0'), autoincrement=False, nullable=False),
    sa.Column('price_quarterly_minor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_yearly_minor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_code'], ['subscription_plans.code'], name=op.f('plan_prices_plan_code_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_prices_pkey')),
    sa.UniqueConstraint('plan_code', name=op.f('plan_prices_plan_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
