"""
Intelligence Service — Database access for structured queries.

Executes SQL generated by the LLM against PostgreSQL.
Read-only — never runs INSERT/UPDATE/DELETE.
Includes row limits, statement timeouts, and regex-based mutation guards.
"""
import json
import re
from typing import List, Dict, Any

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from data_intelligence_service.core.config import SETTINGS
from data_intelligence_service.core.logger import logger

_engine = None
_Session = None

# Regex patterns for forbidden SQL — uses word boundaries to avoid false positives
# e.g. 'CREATED_AT' should not trigger 'CREATE'
_FORBIDDEN_SQL = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|CREATE|GRANT|REVOKE|EXECUTE|EXEC|CALL|COPY|VACUUM|ANALYZE)\b",
    re.IGNORECASE,
)

# Blocks UNION-based injections that bypass the SELECT-only check
_UNION_INJECT = re.compile(r"\bUNION\s+(ALL\s+)?SELECT\b", re.IGNORECASE)


def _get_session():
    global _engine, _Session
    if _engine is None:
        _engine = create_engine(SETTINGS.POSTGRES_URL, pool_pre_ping=True)
        _Session = sessionmaker(bind=_engine)
    return _Session()


def execute_readonly_sql(sql: str, params: Dict[str, Any] = None) -> List[Dict[str, Any]]:
    """Execute a read-only SQL query and return rows as dicts.

    Enforces:
    - SELECT-only (regex word-boundary check)
    - No forbidden DML/DDL keywords
    - No UNION injection
    - Statement timeout
    - Row count cap
    """
    stripped = sql.strip()

    if not re.match(r"^\s*SELECT\b", stripped, re.IGNORECASE):
        raise ValueError(f"Only SELECT queries are allowed. Got: {stripped[:80]}")

    forbidden_match = _FORBIDDEN_SQL.search(stripped)
    if forbidden_match:
        raise ValueError(f"Forbidden SQL keyword detected: {forbidden_match.group()}")

    if _UNION_INJECT.search(stripped):
        raise ValueError("UNION SELECT injection pattern detected")

    session = _get_session()
    try:
        timeout_ms = SETTINGS.SQL_QUERY_TIMEOUT_SECONDS * 1000
        session.execute(text(f"SET LOCAL statement_timeout = '{timeout_ms}'"))

        result = session.execute(text(sql), params or {})
        columns = list(result.keys())
        rows = []
        max_rows = SETTINGS.SQL_MAX_ROWS

        for row in result.fetchmany(max_rows + 1):
            if len(rows) >= max_rows:
                logger.warning(f"[DB] SQL result capped at {max_rows} rows")
                break
            row_dict = {}
            for i, col in enumerate(columns):
                val = row[i]
                if hasattr(val, "isoformat"):
                    val = val.isoformat()
                elif isinstance(val, bytes):
                    val = val.hex()
                else:
                    try:
                        json.dumps(val)
                    except (TypeError, ValueError):
                        val = str(val)
                row_dict[col] = val
            rows.append(row_dict)

        return rows
    except Exception as exc:
        logger.error(f"[DB] SQL execution error: {exc}")
        raise
    finally:
        session.close()


_schema_cache: dict = {"value": None, "expires_at": 0.0}

def get_schema_description() -> str:
    """Return a compact description of the database schema for the LLM.

    Cached for 10 minutes — schema doesn't change at runtime.
    """
    import time
    if _schema_cache["value"] and time.monotonic() < _schema_cache["expires_at"]:
        return _schema_cache["value"]
    session = _get_session()
    try:
        result = session.execute(text("""
            SELECT table_name, column_name, data_type, is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name IN (
                'tenants', 'users', 'sites', 'stores', 'org_units',
                'vendors', 'cost_centres', 'products', 'categories',
                'approved_ranges', 'approved_range_products', 'approved_range_org_units',
                'tenant_subscriptions', 'subscription_plans', 'features', 'plan_features',
                'tenant_roles', 'role_permissions', 'user_roles',
                'orders', 'order_items', 'order_approvals', 'budgets', 'budget_utilization'
              )
            ORDER BY table_name, ordinal_position
        """))

        tables: Dict[str, List[str]] = {}
        for row in result:
            tbl = row[0]
            col = row[1]
            dtype = row[2]
            nullable = "NULL" if row[3] == "YES" else "NOT NULL"
            if tbl not in tables:
                tables[tbl] = []
            tables[tbl].append(f"  {col} {dtype} {nullable}")

        lines = []
        for tbl, cols in sorted(tables.items()):
            lines.append(f"TABLE {tbl} (")
            lines.append(",\n".join(cols))
            lines.append(")\n")
        result = "\n".join(lines)
        _schema_cache["value"] = result
        _schema_cache["expires_at"] = time.monotonic() + 600  # 10 min TTL
        return result
    except Exception as exc:
        logger.error(f"[DB] Schema description error: {exc}")
        return _schema_cache.get("value") or "Schema unavailable"
    finally:
        session.close()
