"""
Intelligence Service — Database access for structured queries.

Executes SQL generated by the LLM against PostgreSQL.
Read-only — never runs INSERT/UPDATE/DELETE.
"""
import json
from typing import List, Dict, Any

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from data_intelligence_service.core.config import SETTINGS
from data_intelligence_service.core.logger import logger

_engine = None
_Session = None


def _get_session():
    global _engine, _Session
    if _engine is None:
        _engine = create_engine(SETTINGS.POSTGRES_URL, pool_pre_ping=True)
        _Session = sessionmaker(bind=_engine)
    return _Session()


def execute_readonly_sql(sql: str, params: Dict[str, Any] = None) -> List[Dict[str, Any]]:
    """Execute a read-only SQL query and return rows as dicts.

    Safety: rejects any statement that isn't a SELECT.
    """
    stripped = sql.strip().upper()
    if not stripped.startswith("SELECT"):
        raise ValueError(f"Only SELECT queries are allowed. Got: {stripped[:50]}")

    for forbidden in ("INSERT ", "UPDATE ", "DELETE ", "DROP ", "ALTER ", "TRUNCATE ", "CREATE ", "GRANT "):
        if forbidden in stripped:
            raise ValueError(f"Forbidden SQL keyword detected: {forbidden.strip()}")

    session = _get_session()
    try:
        result = session.execute(text(sql), params or {})
        columns = result.keys()
        rows = []
        for row in result.fetchall():
            row_dict = {}
            for i, col in enumerate(columns):
                val = row[i]
                if hasattr(val, "isoformat"):
                    val = val.isoformat()
                elif isinstance(val, bytes):
                    val = val.hex()
                else:
                    try:
                        json.dumps(val)
                    except (TypeError, ValueError):
                        val = str(val)
                row_dict[col] = val
            rows.append(row_dict)
        return rows
    except Exception as exc:
        logger.error(f"SQL execution error: {exc}")
        raise
    finally:
        session.close()


def get_schema_description() -> str:
    """Return a compact description of the database schema for the LLM.

    The LLM uses this to generate correct SQL.
    """
    session = _get_session()
    try:
        result = session.execute(text("""
            SELECT table_name, column_name, data_type, is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name IN (
                'tenants', 'users', 'sites', 'stores', 'org_units',
                'vendors', 'cost_centres', 'products', 'categories',
                'approved_ranges', 'approved_range_products', 'approved_range_org_units',
                'tenant_subscriptions', 'subscription_plans', 'features', 'plan_features',
                'tenant_roles', 'role_permissions', 'user_roles'
              )
            ORDER BY table_name, ordinal_position
        """))

        tables: Dict[str, List[str]] = {}
        for row in result:
            tbl = row[0]
            col = row[1]
            dtype = row[2]
            nullable = "NULL" if row[3] == "YES" else "NOT NULL"
            if tbl not in tables:
                tables[tbl] = []
            tables[tbl].append(f"  {col} {dtype} {nullable}")

        lines = []
        for tbl, cols in sorted(tables.items()):
            lines.append(f"TABLE {tbl} (")
            lines.append(",\n".join(cols))
            lines.append(")\n")
        return "\n".join(lines)
    except Exception as exc:
        logger.error(f"Schema description error: {exc}")
        return "Schema unavailable"
    finally:
        session.close()
