"""
Intelligence Service — Neo4j graph access.

Executes Cypher generated by the LLM against Neo4j.
Read-only — never runs CREATE/DELETE/SET.
Graph schema is fetched live from Neo4j (labels + relationship types),
with property hints from a curated static map.
"""
import re
import json
from typing import List, Dict, Any

from neo4j import GraphDatabase

from data_intelligence_service.core.config import SETTINGS
from data_intelligence_service.core.logger import logger

_driver = None

# Regex-based mutation guards — word boundaries prevent false positives
# e.g. 'ERSET' or column name 'deleted_at' won't match
_FORBIDDEN_CYPHER = re.compile(
    r"\b(CREATE|DELETE|DETACH\s+DELETE|SET|REMOVE|MERGE|DROP|CALL\s+apoc\.(?!meta|schema|help))\b",
    re.IGNORECASE,
)

# Property hints per label — static, updated when schema changes
_LABEL_PROPERTIES: Dict[str, List[str]] = {
    "Tenant":        ["tenant_id", "name", "domain", "status"],
    "Site":          ["site_id", "name", "site_type", "currency", "timezone", "geo", "status"],
    "Store":         ["store_id", "name", "store_type", "geo", "status"],
    "OrgUnit":       ["org_unit_id", "name", "code", "level", "status"],
    "User":          ["user_id", "email", "display_name", "status"],
    "Role":          ["role_id", "code", "name", "status"],
    "Permission":    ["code"],
    "Product":       ["product_id", "display_name", "sku", "item_code", "restricted", "status"],
    "Category":      ["category_id", "name", "code", "status"],
    "Vendor":        ["vendor_id", "name", "contact_email", "status"],
    "CostCentre":    ["cost_centre_id", "name", "code", "status"],
    "ApprovedRange": ["approved_range_id", "name", "is_universal", "status"],
    "Policy":        ["policy_id", "code", "name", "policy_type", "status"],
}


def _get_driver():
    global _driver
    if _driver is None:
        _driver = GraphDatabase.driver(
            SETTINGS.NEO4J_URI,
            auth=(SETTINGS.NEO4J_USER, SETTINGS.NEO4J_PASSWORD),
        )
    return _driver


def execute_readonly_cypher(cypher: str, params: Dict[str, Any] = None) -> List[Dict[str, Any]]:
    """Execute a read-only Cypher query and return records as dicts.

    Enforces:
    - No mutation keywords (regex word-boundary check)
    - Row count cap
    """
    cypher = cypher.replace("\\n", " ").replace("\\t", " ")

    forbidden_match = _FORBIDDEN_CYPHER.search(cypher)
    if forbidden_match:
        raise ValueError(f"Forbidden Cypher keyword detected: {forbidden_match.group()}")

    driver = _get_driver()
    max_rows = SETTINGS.CYPHER_MAX_ROWS

    with driver.session(database=SETTINGS.NEO4J_DATABASE) as session:
        result = session.run(cypher, params or {})
        records = []
        for record in result:
            if len(records) >= max_rows:
                logger.warning(f"[Graph] Cypher result capped at {max_rows} rows")
                break
            row = {}
            for key in record.keys():
                val = record[key]
                if hasattr(val, "items"):
                    row[key] = dict(val)
                elif hasattr(val, "isoformat"):
                    row[key] = val.isoformat()
                else:
                    row[key] = val
            records.append(row)
        return records


def get_graph_schema_description() -> str:
    """Return a compact Neo4j schema description for the LLM.

    Labels and relationship types are fetched live from Neo4j.
    Property hints come from the curated static map above.
    Falls back to fully static description if Neo4j is unreachable.
    """
    try:
        driver = _get_driver()
        with driver.session(database=SETTINGS.NEO4J_DATABASE) as session:
            labels_result = session.run("CALL db.labels() YIELD label RETURN label ORDER BY label")
            live_labels = [r["label"] for r in labels_result]

            rels_result = session.run(
                "CALL db.relationshipTypes() YIELD relationshipType RETURN relationshipType ORDER BY relationshipType"
            )
            live_rels = [r["relationshipType"] for r in rels_result]

        lines = ["Neo4j Graph Schema (ZeroQue Governance Topology — live):"]
        lines.append("\nNode labels and key properties:")
        for label in live_labels:
            props = _LABEL_PROPERTIES.get(label, ["(no known properties)"])
            lines.append(f"  :{label:<18} {{{', '.join(props)}}}")

        lines.append("\nRelationship types (live):")
        for rel in live_rels:
            lines.append(f"  [:{rel}]")

        lines.append("""
Known relationship directions:
  (:Tenant)-[:HAS_SITE]->(:Site)
  (:Site)-[:HAS_STORE]->(:Store)
  (:Store)-[:STOCKS]->(:Product)
  (:Tenant)-[:HAS_ORG_UNIT]->(:OrgUnit)
  (:OrgUnit)-[:CHILD_OF]->(:OrgUnit)
  (:Tenant)-[:HAS_USER]->(:User)
  (:User)-[:BELONGS_TO]->(:OrgUnit)
  (:User)-[:HAS_ROLE]->(:Role)
  (:Role)-[:GRANTS]->(:Permission)
  (:User)-[:WORKS_AT]->(:Store)
  (:User)-[:ASSIGNED_TO_CC]->(:CostCentre)
  (:User)-[:MANAGES]->(:CostCentre)
  (:Tenant)-[:HAS_APPROVED_RANGE]->(:ApprovedRange)
  (:OrgUnit)-[:GOVERNED_BY]->(:ApprovedRange)
  (:ApprovedRange)-[:INCLUDES_CATEGORY]->(:Category)
  (:Product)-[:IN_CATEGORY]->(:Category)
  (:Vendor)-[:SUPPLIES]->(:Product)
  (:Policy)-[:ASSIGNED_TO]->(:Tenant | :OrgUnit | :Role)

Notes:
- All status fields: 'active' or 'deleted'. Always filter {status: 'active'}.
- Always filter by tenant_id on the Tenant node or relationship entry point.
- For hybrid steps with prior results: use $prior_ids as a Cypher parameter (list of strings).
""")
        return "\n".join(lines)

    except Exception as exc:
        logger.warning(f"[Graph] Live schema introspection failed ({exc}), using static fallback")
        return _STATIC_SCHEMA_FALLBACK


_STATIC_SCHEMA_FALLBACK = """
Neo4j Graph Schema (ZeroQue Governance Topology — static fallback):

Node labels and key properties:
  :Tenant      {tenant_id, name, domain, status}
  :Site        {site_id, name, site_type, currency, timezone, geo, status}
  :Store       {store_id, name, store_type, geo, status}
  :OrgUnit     {org_unit_id, name, code, level, status}
  :User        {user_id, email, display_name, status}
  :Role        {role_id, code, name, status}
  :Permission  {code}
  :Product     {product_id, display_name, sku, item_code, restricted, status}
  :Category    {category_id, name, code, status}
  :Vendor      {vendor_id, name, contact_email, status}
  :CostCentre  {cost_centre_id, name, code, status}
  :ApprovedRange {approved_range_id, name, is_universal, status}
  :Policy      {policy_id, code, name, policy_type, status}

Relationships:
  (:Tenant)-[:HAS_SITE]->(:Site)
  (:Site)-[:HAS_STORE]->(:Store)
  (:Store)-[:STOCKS]->(:Product)
  (:Tenant)-[:HAS_ORG_UNIT]->(:OrgUnit)
  (:OrgUnit)-[:CHILD_OF]->(:OrgUnit)
  (:Tenant)-[:HAS_USER]->(:User)
  (:User)-[:BELONGS_TO]->(:OrgUnit)
  (:User)-[:HAS_ROLE]->(:Role)
  (:Role)-[:GRANTS]->(:Permission)
  (:User)-[:WORKS_AT]->(:Store)
  (:User)-[:ASSIGNED_TO_CC]->(:CostCentre)
  (:User)-[:MANAGES]->(:CostCentre)
  (:Tenant)-[:HAS_APPROVED_RANGE]->(:ApprovedRange)
  (:OrgUnit)-[:GOVERNED_BY]->(:ApprovedRange)
  (:ApprovedRange)-[:INCLUDES_CATEGORY]->(:Category)
  (:Product)-[:IN_CATEGORY]->(:Category)
  (:Vendor)-[:SUPPLIES]->(:Product)
  (:Policy)-[:ASSIGNED_TO]->(:Tenant | :OrgUnit | :Role)

Notes:
- All status fields: 'active' or 'deleted'. Always filter {status: 'active'}.
- For hybrid steps with prior results: use $prior_ids as a Cypher parameter (list of strings).
"""
