apiVersion: v1
kind: Service
metadata:
  name: provisioning-service
  namespace: zeroque
  labels:
    app: provisioning-service
    version: "4.1"
spec:
  selector:
    app: provisioning-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: provisioning-celery-worker
  namespace: zeroque
  labels:
    app: provisioning-celery-worker
    version: "4.1"
spec:
  selector:
    app: provisioning-celery-worker
  ports:
    - name: worker
      port: 5555
      targetPort: 5555
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: provisioning-celery-beat
  namespace: zeroque
  labels:
    app: provisioning-celery-beat
    version: "4.1"
spec:
  selector:
    app: provisioning-celery-beat
  ports:
    - name: beat
      port: 5556
      targetPort: 5556
      protocol: TCP
  type: ClusterIP




