from typing import Protocol

class EntryVerifyResult(dict): ...
class SyncResult(dict): ...

class CVProvider(Protocol):
    name: str

    async def create_entry_code(self, payload: dict) -> dict: ...
    async def verify_entry_code(self, verification_code: str, *, group_size: int | None = None,
                                check_in_device_id: int | None = None) -> EntryVerifyResult: ...

    async def push_customer(self, customer: dict) -> SyncResult: ...
    async def push_product(self, product: dict) -> SyncResult: ...
    async def update_inventory(self, product_id: str, *, quantity_difference: int | None = None,
                               quantity: int | None = None) -> SyncResult: ...

    def adapt_entry_webhook_to_decision(self, payload: dict) -> dict: ...
    def adapt_checkout_to_order(self, payload: dict) -> dict: ...